env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'airbnb'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
plugins:
  - react
rules: {
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
  "linebreak-style": 0,
  "comma-dangle": ["error", "never"],
  "arrow-body-style": ["error", "always"]
}
